### ISSUE TITLE
generic_const_impls

### ISSUE THREAD

**Issue by Roman-Tarasenko-27** [rust-lang/project-const-generics#17]
Firstly, please check <a href="https://stackoverflow.com/questions/70344477/what-is-going-on-with-unconstrained-generic-constants-in-rust">this</a> question.
I know that you are currently working on this, but how do you think it is possible to fix this issue without fixing this feature?

**Comment by lcnr** [comment]
i think that the main issue in your example is https://github.com/rust-lang/rust/issues/92151 which I did not know about before.

> I know that you are currently working on this, but how do you think it is possible to fix this issue without fixing this feature?

I would assume that this issue gets fixed before we stabilize `generic_const_exprs`, but it will only be relevant while using `generic_const_exprs` so i might be misunderstanding your question.

When encountering bugs or weird error messages in the future, please post them to https://github.com/rust-lang/rust/issues instead of here, as this repository is mostly used for design discussions and internal documentation
